* [0. Cambio de Formato](#section0)
* [1. Variables Predictoras o Variables Features](#section1)
  * [1.1 Forma_1](#section11)
  * [1.2 Forma_2](#section12)
* [2. Variables Y  o Variable Target](#section2)
  * [2.1 Forma_1](#section21)
  * [2.2 Forma_2](#section22)
* [3. Particion train y test](#section3)
* [4 Modelo de Regresion Multiple](#section4)
   * [4.1 Con Statsmodels](#section41)
   * [4.2 Con sklearn.linear_model](#section42)
* [5 Prediccion](#section5)
* [6 Metricas](#section6)
   * [6.1 R2](#section61)
    * [6.1.1 Forma_1](#section611)
    * [6.1.2 Forma_2](#section612)
    * [6.1.3 Forma_3 -->Recomendada](#section613)
   * [6.2 Mape](#section62)
    * [6.2.1 Forma_1 -->Recomendada](#section621)
    * [6.2.2 Forma_2](#section622)
   * [6.3 MAE](#section63)
    * [6.3.1 Forma_1 -->Recomendada](#section631)
    * [6.3.2 Forma_2](#section632)
   * [6.4 RMSE](#section64)
    * [6.4.1 Forma_1 -->Recomendada](#section641)
    * [6.4.2 Forma_2](#section642)
   * [6.5 MSE](#section65)
    * [6.5.1 Forma_1 -->Recomendada](#section651)
    * [6.5.2 Forma_2](#section652)
   * [6.6 Suma de errores al cuadrado(RSS)](#section66)
   * [6.7 Validacion Cruzada](#section67)

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

### Cargando nuestra informacion! 

In [2]:
df=pd.read_csv('Datos_unalm/Advertising.csv')

In [3]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
df.shape

(200, 4)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


<a id="section0"></a>
## <font color="#004D7F">0. Cambio de Formato</font>

- **float** // **str** // **int**

### variable_Sales -> Cambiar Formato  de: 'float64' -->'object'

In [6]:
df['Sales']=df['Sales'].astype(str)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    object 
dtypes: float64(3), object(1)
memory usage: 6.4+ KB


### En este caso deseamos que la variable target(Sales) sea 'float'

In [8]:
df['Sales']=df['Sales'].astype(float)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


<a id="section1"></a>
## <font color="#004D7F">1. Variables Predictoras o Variables Features</font>

<a id="section11"></a>
## <font color="#004D7F">1.1 Forma_1</font>

In [10]:
df.columns

Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [11]:
lista=['TV', 'Radio', 'Newspaper']

In [12]:
x=df[lista]

In [13]:
x.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

<a id="section12"></a>
## <font color="#004D7F">1.2 Forma_2</font>

In [14]:
x1=df.iloc[:,0:3]

In [15]:
x1.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

<a id="section2"></a>
## <font color="#004D7F">2. Variables Y  o Variable Target</font>

<a id="section21"></a>
## <font color="#004D7F">2.1 Forma_1</font>

In [16]:
df.columns

Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [17]:
lista1=['Sales']

In [18]:
y=df[lista1]

In [19]:
y.head()

Sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

<a id="section11"></a>
## <font color="#004D7F">2.2 Forma_2</font>

In [20]:
y1=df.iloc[:,3]

In [21]:
y1

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [22]:
df.columns

Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

<a id="section3"></a>
## <font color="#004D7F">3. Particion train y test </font>

In [23]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,
                                           random_state=4)

In [24]:
print(len(xtrain))#entrenamiento 
print(len(xtest))#testeo

140
60


In [25]:
xtrain.columns

Index(['TV', 'Radio', 'Newspaper'], dtype='object')

In [26]:
xtrain.shape

(140, 3)

In [27]:
ytrain.shape

(140, 1)

In [28]:
data_entrenamiento=pd.concat([ytrain,xtrain],axis=1)

In [29]:
data_entrenamiento.head()

Sales     TV  Radio  Newspaper
77    14.2  120.5   28.5       14.2
127    8.8   80.2    0.0        9.2
5      7.2    8.7   48.9       75.0
118   15.9  125.7   36.9       79.2
113   15.9  209.6   20.6       10.7

In [30]:
data_entrenamiento.shape

(140, 4)

<a id="section4"></a>
## <font color="#004D7F">4 Modelo de Regresion Multiple </font>

### Data Inicial // Data Original // Data Sin Particionar

In [31]:
import statsmodels.formula.api as smf
lm = smf.ols(formula='Sales~TV+Radio+Newspaper', data=df).fit()#modelo de regresion lineal
lm.summary()
#¿cuando uso r-ajustado o r2?

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Thu, 21 Apr 2022   Prob (F-statistic):           1.58e-96
Time:                        10:28:25   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9389      0.312      9.422      0.000       2.324       3.554
TV             0.0458      0.001     32.809      0.000       0.043       0.049
Radio          0.1885      0.009     21.893      0.000       0.172       0.206
Newspaper     -0.0010      0.006     -0.177      0.860      -0.013       0.011
==============================================================================
Omnibus:                       60.414   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              151.241
Skew:                          -1.327   Prob(JB):                     1.44e-33
Kurtosis:                       6.332   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

<a id="section41"></a>
## <font color="#004D7F">4.1 Con Statsmodels </font>

### Data Entrenamiento

In [32]:
import statsmodels.formula.api as smf
lm=smf.ols(formula='Sales~TV+Radio+Newspaper',data=data_entrenamiento).fit()#modelo de regresion lineal
lm.summary()
#¿cuando uso r-ajustado o r2?

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.889
Model:                            OLS   Adj. R-squared:                  0.887
Method:                 Least Squares   F-statistic:                     363.1
Date:                Thu, 21 Apr 2022   Prob (F-statistic):           1.06e-64
Time:                        10:28:25   Log-Likelihood:                -277.23
No. Observations:                 140   AIC:                             562.5
Df Residuals:                     136   BIC:                             574.2
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.0906      0.376      8.224      0.000       2.347       3.834
TV             0.0453      0.002     25.906      0.000       0.042       0.049
Radio          0.1772      0.011     16.230      0.000       0.156       0.199
Newspaper      0.0055      0.008      0.734      0.464      -0.009       0.020
==============================================================================
Omnibus:                       52.813   Durbin-Watson:                   1.857
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              131.947
Skew:                          -1.546   Prob(JB):                     2.23e-29
Kurtosis:                       6.614   Cond. No.                         434.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

####  ---------------------------------------------------------------------------------------------------

<a id="section42"></a>
## <font color="#004D7F">4.2 Con sklearn.linear_model </font>

### Data Entrenamiento

In [33]:
from sklearn.linear_model import LinearRegression

### paso 1 : modelito

In [34]:
rm_modelito= LinearRegression()

### paso 2: ajustar

In [35]:
rm_modelito.fit(xtrain,ytrain) ######   x,y  estan en formato pandas

LinearRegression()

### coeficientes de la regresion lineal multiple

In [36]:
rm_modelito.coef_

array([[0.04533392, 0.17715767, 0.00553852]])

In [37]:
rm_modelito.intercept_

array([3.09064436])

In [38]:
pd.DataFrame(list(zip(x.columns, np.transpose(rm_modelito.coef_))))

0                       1
0         TV   [0.04533391693312688]
1      Radio   [0.17715766675060451]
2  Newspaper  [0.005538520451028317]

#### Con la data de entrenamiento Observamos las metricas: RMSE,MSE,MAPE

<a id="section5"></a>
## <font color="#004D7F">5 Prediccion </font>

In [39]:
y_predicho_train=rm_modelito.predict(xtrain)

In [40]:
y_predicho_train

array([[13.68102185],
       [ 6.77737889],
       [12.56344838],
       [15.76488645],
       [16.30134346],
       [15.73698411],
       [17.06312697],
       [15.48178708],
       [ 4.83570206],
       [19.29752778],
       [19.22139262],
       [ 9.93408152],
       [12.01869557],
       [10.28059086],
       [ 4.73542672],
       [23.51727736],
       [17.24615447],
       [10.24655613],
       [ 9.50128112],
       [17.88907995],
       [18.19459618],
       [17.19553546],
       [14.50003194],
       [ 7.8712356 ],
       [ 7.51427792],
       [17.04263787],
       [10.18600684],
       [17.35550978],
       [21.31791908],
       [ 9.10868279],
       [12.05358847],
       [16.77633225],
       [21.33161399],
       [ 6.81270325],
       [ 8.0663848 ],
       [10.28914909],
       [13.03682814],
       [12.07631829],
       [ 7.24876294],
       [19.81418283],
       [ 8.89697688],
       [20.69230017],
       [11.51007439],
       [14.10457312],
       [ 5.98884859],
       [15

In [41]:
ytrain

Sales
77    14.2
127    8.8
5      7.2
118   15.9
113   15.9
..     ...
104   20.7
129    9.7
183   26.2
174   11.5
122   11.6

[140 rows x 1 columns]

In [42]:
y_real_train=ytrain

<a id="section6"></a>
## <font color="#004D7F">6 Metricas </font>

<a id="section51"></a>
## <font color="#004D7F">6.1 R2 </font>

<a id="section611"></a>
## <font color="#004D7F">6.1.1 Forma_1 </font>

In [43]:
### ytrain=y_real_train

In [44]:
rm_modelito.score(xtrain,y_real_train) # coeficiente de determinacion  R2

0.8890066696510228

<a id="section612"></a>
## <font color="#004D7F">6.1.2 Forma_2 </font>

In [45]:
data_entrenamiento['y_predicho']=y_predicho_train

In [46]:
data_entrenamiento.head(2)

Sales     TV  Radio  Newspaper  y_predicho
77    14.2  120.5   28.5       14.2   13.681022
127    8.8   80.2    0.0        9.2    6.777379

**rss: la suma  de los errores al cuadrado   de la linea de regresion**<br>
**tss: la suma  de y_real- y_real_media al cuadrado**

In [47]:
rss=((y_real_train-y_predicho_train)**2).sum()   ;rss

Sales    430.157339
dtype: float64

In [48]:
tss=((y_real_train-y_real_train.mean())**2).sum()
tss

Sales    3875.524214
dtype: float64

In [49]:
r2=1-rss/tss
r2

Sales    0.889007
dtype: float64

<a id="section613"></a>
## <font color="#004D7F">6.1.3 Forma_3 -->Recomendada </font>

In [50]:
from sklearn.metrics import r2_score
r2_score(data_entrenamiento.Sales,data_entrenamiento.y_predicho) #y_real , y_predicho

0.8890066696510228

<a id="section62"></a>
## <font color="#004D7F">6.2 Mape </font>

<a id="section621"></a>
## <font color="#004D7F">6.2.1 Forma_1 -->Recomendada </font>

In [51]:
### Modelo con 4 variables (LSTATA, INDUS, NOX, RM)
def mean_absolute_percentage_error(y_true, y_pred):
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

In [52]:
mean_absolute_percentage_error(data_entrenamiento.Sales,data_entrenamiento.y_predicho) ### formato numpy

15.303213566902635

<a id="section622"></a>
## <font color="#004D7F">6.2.2 Forma_2 </font>

In [53]:
mape=(( abs(data_entrenamiento.Sales-data_entrenamiento.y_predicho)/data_entrenamiento.Sales).mean())*100
mape

15.303213566902635

<a id="section63"></a>
## <font color="#004D7F">6.3 MAE</font>

### Es mas robusto para valores atipicos en comparacion MSE Y RMSE

<a id="section631"></a>
## <font color="#004D7F">6.3.1 Forma_1 -->Recomendada </font>

In [54]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(data_entrenamiento.Sales,data_entrenamiento.y_predicho)

1.290268303086694

<a id="section632"></a>
## <font color="#004D7F">6.3.2 Forma_2 </font>

In [55]:
((abs(data_entrenamiento.Sales-data_entrenamiento.y_predicho)  ).sum() )/ data_entrenamiento.shape[0]

1.290268303086694

<a id="section64"></a>
## <font color="#004D7F">6.4 RMSE</font>

### sensible a valores atipicos

<a id="section641"></a>
## <font color="#004D7F">6.4.1 Forma_1 -->Recomendada </font>

In [56]:
from sklearn.metrics import mean_squared_error
mean_squared_error(data_entrenamiento.Sales,data_entrenamiento.y_predicho)**0.5

1.7528697681876557

<a id="section642"></a>
## <font color="#004D7F">6.4.2 Forma_2</font>

In [57]:
((((data_entrenamiento.Sales-data_entrenamiento.y_predicho)**2 ).sum()   ) / data_entrenamiento.shape[0]  )**0.5

1.7528697681876557

<a id="section65"></a>
## <font color="#004D7F">6.5 MSE</font>

### sensible a valores atipicos

<a id="section651"></a>
## <font color="#004D7F">6.5.1 Forma_1 -->Recomendada </font>

In [58]:
from sklearn.metrics import mean_squared_error
mean_squared_error(data_entrenamiento.Sales,data_entrenamiento.y_predicho)

3.072552424226246

<a id="section652"></a>
## <font color="#004D7F">6.5.2 Forma_2 </font>

In [59]:
( ((data_entrenamiento.Sales-data_entrenamiento.y_predicho)**2).sum()    )/ data_entrenamiento.shape[0]

3.072552424226246

<a id="section66"></a>
## <font color="#004D7F">6.6 Suma de errores al cuadrado(RSS)</font>

In [60]:
rss=((data_entrenamiento.Sales-data_entrenamiento.y_predicho)**2).sum()

###  Error estandar Residual

In [61]:
data_entrenamiento.columns # tenemos 3 predictores

Index(['Sales', 'TV', 'Radio', 'Newspaper', 'y_predicho'], dtype='object')

In [62]:
len(data_entrenamiento.Sales)

140

In [63]:
RSE = np.sqrt(rss/(len(data_entrenamiento.Sales)-3))  # np.sqrt(RSS/(numero.d.observaciones - numero.d.predictores ))
RSE                                 #n=numero.d.observaciones 
                                    #p=numero.d.predictores 

1.7719578420774613

### EL R-AJUSTADO SE UTLIZA CUANDO SE TIENE DIFERENTES NUMERO DE PREDICTORES -->Error estandar Residual

### error

In [64]:
sales_mean = np.mean(data_entrenamiento.Sales)
error = RSE/sales_mean
error

0.12787983807971784

<a id="section67"></a>
## <font color="#004D7F">6.7 Validacion Cruzada</font>

In [65]:
data_entrenamiento.columns

Index(['Sales', 'TV', 'Radio', 'Newspaper', 'y_predicho'], dtype='object')

In [66]:
data_entrenamiento_xtrain=data_entrenamiento[['TV', 'Radio', 'Newspaper']]
data_entrenamiento_ytrain=data_entrenamiento[['Sales']]

In [67]:
# Validación cruzada: Cross Validation (K-Fold)
from sklearn.model_selection import cross_val_score
cv_reg_train=cross_val_score(rm_modelito,data_entrenamiento_xtrain,data_entrenamiento_ytrain,cv=10)
np.mean(cv_reg_train)
print(cv_reg_train)
print("promedio:",np.mean(cv_reg_train))

[0.71992597 0.756014   0.94590806 0.91402088 0.89314676 0.93962354
 0.92563716 0.89872719 0.75336329 0.9057542 ]
promedio: 0.8652121039042037


### NOTA: solo se uso la data de entrenamiento, en la data de testeo lo predecira bien el modelo ya que  nuestras metricas nos dieron un buen indicador

In [68]:
rm_modelito.predict(xtest)

array([[17.09777441],
       [16.86148273],
       [21.7761552 ],
       [24.53812602],
       [12.32008724],
       [20.9083371 ],
       [10.09857022],
       [12.38326275],
       [12.01767713],
       [16.939182  ],
       [22.8039863 ],
       [15.18438755],
       [ 8.45988902],
       [14.86958246],
       [18.5360064 ],
       [18.5391287 ],
       [18.67614759],
       [14.5131948 ],
       [ 9.74192603],
       [20.57441729],
       [14.89243548],
       [17.70102466],
       [23.04193509],
       [ 7.718106  ],
       [21.42075683],
       [19.62792915],
       [13.79733409],
       [11.63827129],
       [18.42655599],
       [12.19463761],
       [11.40777433],
       [ 9.96083851],
       [13.49436555],
       [15.18912412],
       [18.09830593],
       [ 6.92815403],
       [14.21050378],
       [14.27217178],
       [14.10451207],
       [10.77723418],
       [14.82936609],
       [11.96507878],
       [10.69651541],
       [10.40851022],
       [ 6.21159776],
       [16

In [69]:
ytest

Sales
11    17.4
99    17.2
128   24.7
175   27.0
1     10.4
111   21.8
90    11.2
177   11.7
88    12.9
187   17.3
61    24.2
199   13.4
191    9.9
123   15.2
184   17.6
188   15.9
33    17.4
171   14.5
138    9.6
84    21.7
81    12.3
102   14.8
147   25.4
34     9.5
47    23.2
124   19.7
112   14.1
6     11.8
14    19.0
190   10.8
80    11.8
18    11.3
167   12.2
45    14.9
153   19.0
119    6.6
100   11.7
83    13.6
181   12.2
71    12.4
26    15.0
134   10.8
180   10.5
158    7.3
189    6.7
89    16.7
48    14.8
116   12.2
12     9.2
69    22.3
110   13.4
154   15.6
16    12.5
19    14.6
2      9.3
143   10.4
185   22.6
29    10.5
155    3.2
24     9.7